# Generated by Django 3.2.4 on 2021-07-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=400, verbose_name='Логин клиента')),
                ('spent_money', models.BigIntegerField(verbose_name='Сумма потраченных средств за весь период')),
                ('gems', models.CharField(db_index=True, max_length=400, verbose_name='Список из названии камней,которые купили как минимум двое из списка клиентов')),
            ],
            options={
                'verbose_name': '5 клиентов,потратившиx наибольшую сумму за весь период',
                'ordering': ['spent_money'],
            },
        ),
        migrations.CreateModel(
            name='fileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(db_index=True, max_length=400, unique=True, verbose_name='Название файлов')),
                ('reletedFile', models.ManyToManyField(blank=True, to='ApiRestService.response')),
            ],
            options={
                'verbose_name': 'Файлы',
                'ordering': ['id'],
            },
        ),
    ]
